// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: proto/orderinfo.proto

package orderinfo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取订单信息
type OrderInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId *int64 `protobuf:"varint,1,req,name=order_id,json=orderId" json:"order_id,omitempty"`
}

func (x *OrderInfoReq) Reset() {
	*x = OrderInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_orderinfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoReq) ProtoMessage() {}

func (x *OrderInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderinfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoReq.ProtoReflect.Descriptor instead.
func (*OrderInfoReq) Descriptor() ([]byte, []int) {
	return file_proto_orderinfo_proto_rawDescGZIP(), []int{0}
}

func (x *OrderInfoReq) GetOrderId() int64 {
	if x != nil && x.OrderId != nil {
		return *x.OrderId
	}
	return 0
}

type OrderInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId *int64  `protobuf:"varint,1,req,name=order_id,json=orderId" json:"order_id,omitempty"`
	Price   *string `protobuf:"bytes,2,req,name=price" json:"price,omitempty"`
	Desc    *string `protobuf:"bytes,3,req,name=desc" json:"desc,omitempty"`
	UserId  *int64  `protobuf:"varint,4,req,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (x *OrderInfoRsp) Reset() {
	*x = OrderInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_orderinfo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoRsp) ProtoMessage() {}

func (x *OrderInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderinfo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoRsp.ProtoReflect.Descriptor instead.
func (*OrderInfoRsp) Descriptor() ([]byte, []int) {
	return file_proto_orderinfo_proto_rawDescGZIP(), []int{1}
}

func (x *OrderInfoRsp) GetOrderId() int64 {
	if x != nil && x.OrderId != nil {
		return *x.OrderId
	}
	return 0
}

func (x *OrderInfoRsp) GetPrice() string {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return ""
}

func (x *OrderInfoRsp) GetDesc() string {
	if x != nil && x.Desc != nil {
		return *x.Desc
	}
	return ""
}

func (x *OrderInfoRsp) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

// 获取所有订单
type GetAllReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllReq) Reset() {
	*x = GetAllReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_orderinfo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllReq) ProtoMessage() {}

func (x *GetAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderinfo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllReq.ProtoReflect.Descriptor instead.
func (*GetAllReq) Descriptor() ([]byte, []int) {
	return file_proto_orderinfo_proto_rawDescGZIP(), []int{2}
}

// 上传图片 order_id 不在请求中写，写在 metadata
type AddImageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,req,name=data" json:"data,omitempty"`
}

func (x *AddImageReq) Reset() {
	*x = AddImageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_orderinfo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddImageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddImageReq) ProtoMessage() {}

func (x *AddImageReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderinfo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddImageReq.ProtoReflect.Descriptor instead.
func (*AddImageReq) Descriptor() ([]byte, []int) {
	return file_proto_orderinfo_proto_rawDescGZIP(), []int{3}
}

func (x *AddImageReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddImageRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *bool `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
}

func (x *AddImageRsp) Reset() {
	*x = AddImageRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_orderinfo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddImageRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddImageRsp) ProtoMessage() {}

func (x *AddImageRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderinfo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddImageRsp.ProtoReflect.Descriptor instead.
func (*AddImageRsp) Descriptor() ([]byte, []int) {
	return file_proto_orderinfo_proto_rawDescGZIP(), []int{4}
}

func (x *AddImageRsp) GetResult() bool {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return false
}

//
type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId            *int64  `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	Name              *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	OrderNum          *int32  `protobuf:"varint,3,req,name=order_num,json=orderNum" json:"order_num,omitempty"`
	ConsumptionAmount *int32  `protobuf:"varint,4,req,name=consumption_amount,json=consumptionAmount" json:"consumption_amount,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_orderinfo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderinfo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_orderinfo_proto_rawDescGZIP(), []int{5}
}

func (x *User) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *User) GetOrderNum() int32 {
	if x != nil && x.OrderNum != nil {
		return *x.OrderNum
	}
	return 0
}

func (x *User) GetConsumptionAmount() int32 {
	if x != nil && x.ConsumptionAmount != nil {
		return *x.ConsumptionAmount
	}
	return 0
}

type AddBatchUsersRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId *int64 `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (x *AddBatchUsersRsp) Reset() {
	*x = AddBatchUsersRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_orderinfo_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBatchUsersRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBatchUsersRsp) ProtoMessage() {}

func (x *AddBatchUsersRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderinfo_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBatchUsersRsp.ProtoReflect.Descriptor instead.
func (*AddBatchUsersRsp) Descriptor() ([]byte, []int) {
	return file_proto_orderinfo_proto_rawDescGZIP(), []int{6}
}

func (x *AddBatchUsersRsp) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

var File_proto_orderinfo_proto protoreflect.FileDescriptor

var file_proto_orderinfo_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x66,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x03, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x6c, 0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x73, 0x70, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x03, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x03, 0x20, 0x02, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x02, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x0b, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x22, 0x21, 0x0a,
	0x0b, 0x41, 0x64, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x25, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x73, 0x70, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x08, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x7f, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x03,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x02, 0x28, 0x05, 0x52,
	0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x12, 0x2d, 0x0a, 0x12, 0x63, 0x6f, 0x6e,
	0x73, 0x75, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x04, 0x20, 0x02, 0x28, 0x05, 0x52, 0x11, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2b, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x73, 0x70, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x03, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x32, 0xc0, 0x01, 0x0a, 0x10, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2c, 0x0a, 0x0c, 0x47, 0x65,
	0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0d, 0x2e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x12, 0x25, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x12, 0x0a, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x0d,
	0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x30, 0x01, 0x12,
	0x28, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x0c, 0x2e, 0x41, 0x64,
	0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x41, 0x64, 0x64, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x52, 0x73, 0x70, 0x28, 0x01, 0x12, 0x2d, 0x0a, 0x0d, 0x41, 0x64, 0x64,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x05, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x1a, 0x11, 0x2e, 0x41, 0x64, 0x64, 0x42, 0x61, 0x74, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x52, 0x73, 0x70, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f,
}

var (
	file_proto_orderinfo_proto_rawDescOnce sync.Once
	file_proto_orderinfo_proto_rawDescData = file_proto_orderinfo_proto_rawDesc
)

func file_proto_orderinfo_proto_rawDescGZIP() []byte {
	file_proto_orderinfo_proto_rawDescOnce.Do(func() {
		file_proto_orderinfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_orderinfo_proto_rawDescData)
	})
	return file_proto_orderinfo_proto_rawDescData
}

var file_proto_orderinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_orderinfo_proto_goTypes = []interface{}{
	(*OrderInfoReq)(nil),     // 0: OrderInfoReq
	(*OrderInfoRsp)(nil),     // 1: OrderInfoRsp
	(*GetAllReq)(nil),        // 2: GetAllReq
	(*AddImageReq)(nil),      // 3: AddImageReq
	(*AddImageRsp)(nil),      // 4: AddImageRsp
	(*User)(nil),             // 5: User
	(*AddBatchUsersRsp)(nil), // 6: AddBatchUsersRsp
}
var file_proto_orderinfo_proto_depIdxs = []int32{
	0, // 0: OrderInfoService.GetOrderInfo:input_type -> OrderInfoReq
	2, // 1: OrderInfoService.GetAll:input_type -> GetAllReq
	3, // 2: OrderInfoService.AddImage:input_type -> AddImageReq
	5, // 3: OrderInfoService.AddBatchUsers:input_type -> User
	1, // 4: OrderInfoService.GetOrderInfo:output_type -> OrderInfoRsp
	1, // 5: OrderInfoService.GetAll:output_type -> OrderInfoRsp
	4, // 6: OrderInfoService.AddImage:output_type -> AddImageRsp
	6, // 7: OrderInfoService.AddBatchUsers:output_type -> AddBatchUsersRsp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_orderinfo_proto_init() }
func file_proto_orderinfo_proto_init() {
	if File_proto_orderinfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_orderinfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_orderinfo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_orderinfo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_orderinfo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddImageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_orderinfo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddImageRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_orderinfo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_orderinfo_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddBatchUsersRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_orderinfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_orderinfo_proto_goTypes,
		DependencyIndexes: file_proto_orderinfo_proto_depIdxs,
		MessageInfos:      file_proto_orderinfo_proto_msgTypes,
	}.Build()
	File_proto_orderinfo_proto = out.File
	file_proto_orderinfo_proto_rawDesc = nil
	file_proto_orderinfo_proto_goTypes = nil
	file_proto_orderinfo_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OrderInfoServiceClient is the client API for OrderInfoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderInfoServiceClient interface {
	GetOrderInfo(ctx context.Context, in *OrderInfoReq, opts ...grpc.CallOption) (*OrderInfoRsp, error)
	// 服务端流模式
	GetAll(ctx context.Context, in *GetAllReq, opts ...grpc.CallOption) (OrderInfoService_GetAllClient, error)
	// 图片上传,客户端流
	AddImage(ctx context.Context, opts ...grpc.CallOption) (OrderInfoService_AddImageClient, error)
	// 批量上传客户信息
	AddBatchUsers(ctx context.Context, opts ...grpc.CallOption) (OrderInfoService_AddBatchUsersClient, error)
}

type orderInfoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderInfoServiceClient(cc grpc.ClientConnInterface) OrderInfoServiceClient {
	return &orderInfoServiceClient{cc}
}

func (c *orderInfoServiceClient) GetOrderInfo(ctx context.Context, in *OrderInfoReq, opts ...grpc.CallOption) (*OrderInfoRsp, error) {
	out := new(OrderInfoRsp)
	err := c.cc.Invoke(ctx, "/OrderInfoService/GetOrderInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderInfoServiceClient) GetAll(ctx context.Context, in *GetAllReq, opts ...grpc.CallOption) (OrderInfoService_GetAllClient, error) {
	stream, err := c.cc.NewStream(ctx, &_OrderInfoService_serviceDesc.Streams[0], "/OrderInfoService/GetAll", opts...)
	if err != nil {
		return nil, err
	}
	x := &orderInfoServiceGetAllClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type OrderInfoService_GetAllClient interface {
	Recv() (*OrderInfoRsp, error)
	grpc.ClientStream
}

type orderInfoServiceGetAllClient struct {
	grpc.ClientStream
}

func (x *orderInfoServiceGetAllClient) Recv() (*OrderInfoRsp, error) {
	m := new(OrderInfoRsp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *orderInfoServiceClient) AddImage(ctx context.Context, opts ...grpc.CallOption) (OrderInfoService_AddImageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_OrderInfoService_serviceDesc.Streams[1], "/OrderInfoService/AddImage", opts...)
	if err != nil {
		return nil, err
	}
	x := &orderInfoServiceAddImageClient{stream}
	return x, nil
}

type OrderInfoService_AddImageClient interface {
	Send(*AddImageReq) error
	CloseAndRecv() (*AddImageRsp, error)
	grpc.ClientStream
}

type orderInfoServiceAddImageClient struct {
	grpc.ClientStream
}

func (x *orderInfoServiceAddImageClient) Send(m *AddImageReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *orderInfoServiceAddImageClient) CloseAndRecv() (*AddImageRsp, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(AddImageRsp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *orderInfoServiceClient) AddBatchUsers(ctx context.Context, opts ...grpc.CallOption) (OrderInfoService_AddBatchUsersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_OrderInfoService_serviceDesc.Streams[2], "/OrderInfoService/AddBatchUsers", opts...)
	if err != nil {
		return nil, err
	}
	x := &orderInfoServiceAddBatchUsersClient{stream}
	return x, nil
}

type OrderInfoService_AddBatchUsersClient interface {
	Send(*User) error
	Recv() (*AddBatchUsersRsp, error)
	grpc.ClientStream
}

type orderInfoServiceAddBatchUsersClient struct {
	grpc.ClientStream
}

func (x *orderInfoServiceAddBatchUsersClient) Send(m *User) error {
	return x.ClientStream.SendMsg(m)
}

func (x *orderInfoServiceAddBatchUsersClient) Recv() (*AddBatchUsersRsp, error) {
	m := new(AddBatchUsersRsp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// OrderInfoServiceServer is the server API for OrderInfoService service.
type OrderInfoServiceServer interface {
	GetOrderInfo(context.Context, *OrderInfoReq) (*OrderInfoRsp, error)
	// 服务端流模式
	GetAll(*GetAllReq, OrderInfoService_GetAllServer) error
	// 图片上传,客户端流
	AddImage(OrderInfoService_AddImageServer) error
	// 批量上传客户信息
	AddBatchUsers(OrderInfoService_AddBatchUsersServer) error
}

// UnimplementedOrderInfoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrderInfoServiceServer struct {
}

func (*UnimplementedOrderInfoServiceServer) GetOrderInfo(context.Context, *OrderInfoReq) (*OrderInfoRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderInfo not implemented")
}
func (*UnimplementedOrderInfoServiceServer) GetAll(*GetAllReq, OrderInfoService_GetAllServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (*UnimplementedOrderInfoServiceServer) AddImage(OrderInfoService_AddImageServer) error {
	return status.Errorf(codes.Unimplemented, "method AddImage not implemented")
}
func (*UnimplementedOrderInfoServiceServer) AddBatchUsers(OrderInfoService_AddBatchUsersServer) error {
	return status.Errorf(codes.Unimplemented, "method AddBatchUsers not implemented")
}

func RegisterOrderInfoServiceServer(s *grpc.Server, srv OrderInfoServiceServer) {
	s.RegisterService(&_OrderInfoService_serviceDesc, srv)
}

func _OrderInfoService_GetOrderInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderInfoServiceServer).GetOrderInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OrderInfoService/GetOrderInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderInfoServiceServer).GetOrderInfo(ctx, req.(*OrderInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderInfoService_GetAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetAllReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrderInfoServiceServer).GetAll(m, &orderInfoServiceGetAllServer{stream})
}

type OrderInfoService_GetAllServer interface {
	Send(*OrderInfoRsp) error
	grpc.ServerStream
}

type orderInfoServiceGetAllServer struct {
	grpc.ServerStream
}

func (x *orderInfoServiceGetAllServer) Send(m *OrderInfoRsp) error {
	return x.ServerStream.SendMsg(m)
}

func _OrderInfoService_AddImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrderInfoServiceServer).AddImage(&orderInfoServiceAddImageServer{stream})
}

type OrderInfoService_AddImageServer interface {
	SendAndClose(*AddImageRsp) error
	Recv() (*AddImageReq, error)
	grpc.ServerStream
}

type orderInfoServiceAddImageServer struct {
	grpc.ServerStream
}

func (x *orderInfoServiceAddImageServer) SendAndClose(m *AddImageRsp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *orderInfoServiceAddImageServer) Recv() (*AddImageReq, error) {
	m := new(AddImageReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _OrderInfoService_AddBatchUsers_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrderInfoServiceServer).AddBatchUsers(&orderInfoServiceAddBatchUsersServer{stream})
}

type OrderInfoService_AddBatchUsersServer interface {
	Send(*AddBatchUsersRsp) error
	Recv() (*User, error)
	grpc.ServerStream
}

type orderInfoServiceAddBatchUsersServer struct {
	grpc.ServerStream
}

func (x *orderInfoServiceAddBatchUsersServer) Send(m *AddBatchUsersRsp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *orderInfoServiceAddBatchUsersServer) Recv() (*User, error) {
	m := new(User)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _OrderInfoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "OrderInfoService",
	HandlerType: (*OrderInfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrderInfo",
			Handler:    _OrderInfoService_GetOrderInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAll",
			Handler:       _OrderInfoService_GetAll_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AddImage",
			Handler:       _OrderInfoService_AddImage_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "AddBatchUsers",
			Handler:       _OrderInfoService_AddBatchUsers_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/orderinfo.proto",
}
